export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_LAST_FIVE_DRAWS = 'UPDATE_LAST_FIVE_DRAWS';
export const SET_LAST_FIVE_DRAWS = 'SET_LAST_FIVE_DRAWS';
